stages:
  - test
  - deploy

before_script:
  - echo "Start job $CI_BUILD_NAME" at `date +%Y-%m-%d-%H-%M-%S`
  - echo "CI_PIPELINE_ID $CI_PIPELINE_ID"

test_py2:
  image: python:2.7
  script:
    - python setup.py install
    - pip install pytest
    - pytest .

test_py3:
  image: python:3.6
  script:
    - python3 setup.py install
    - pip3 install pytest
    - pytest .

deploy_pypi:
  image: python:3.6
  stage: deploy
  only:
    refs:
      - master
    variables:
      - $PYPI_LOGIN
      - $PYPI_PASSWORD
  script:
    - python setup.py bdist_wheel --universal
    - pip install twine
    - twine upload -u "$PYPI_LOGIN" -p "$PYPI_PASSWORD" --skip-existing dist/*
