test_py2:
  image: python:2.7
  script:
    - python setup.py install
    - pip install pytest
    - pytest .

test_py3:
  image: python:3.6
  script:
    - python3 setup.py install
    - pip3 install pytest
    - pytest .