language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - os: osx
      language: generic

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew update || brew update
      brew install libmagic
      # The following wasn't required in the past and therefore may become
      # obsolete once again in the future. Let's wait and see.
      wget https://bootstrap.pypa.io/get-pip.py
      sudo python get-pip.py
      sudo pip install virtualenv
      virtualenv $HOME
      source $HOME/bin/activate
    fi

install:
  - pip install -e .
  - pip install pytest pytest-cov codecov coveralls

script:
  - py.test --cov=roach

after_success:
  - codecov
  - coveralls
